### ISSUE TITLE
# Use protobuf for received time series

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/geh-timeseries#111]
**Description**
Update message receiver to send protobuf messages and streaming job to consume them.

**Acceptance criteria**
1) Messages on the Eventhub is stored in protobuf format
2) The streaming job can consume the protobuf message from the Eventhub
3) The streaming job can validate timeseries in the protobuf format.
4) Updated architectural drawing for Time series domain

**Note**
The protobuf consumption code will be written in python.

**Comment by BjarkeMeier** [comment]
Some time has been spent on finding a solution for using ProtoBuf in Pyspark as this isn't natively supported. Solutions exist for using Protobuf with Python and for using ProtoBuf with Spark using Scala API (ScalaPB). The architect found https://github.com/aroch/protobuf-dataframe which seems promising. It however uses UDF (user-defined functions), which is known to potentially have poor performance. So it has been agreed to make some performance analysis comparison between a JSON-based implementation and a ProtoBuf solution based on https://github.com/aroch/protobuf-dataframe. However, it is necessary to fix the types and presumably extend https://github.com/aroch/protobuf-dataframe to support the necessary types. One of these will most likely be a custom type for measure quality decimal(precision=18, scale=3). See https://docs.microsoft.com/en-us/aspnet/core/grpc/protobuf?view=aspnetcore-5.0#decimals.

**Comment by lasrinnil** [comment]
### Test
I have verified that a proto contract is present which is registered when sending the message to the EventHub. And verified we now use a protobuf parser in the streaming job when reading from the EventHub.
