### ISSUE TITLE
# Setup development environment for streaming job

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/geh-timeseries#113]
**Synopsis**

As a Databricks developer
I want a good developer experience
So that I can be productive and efficient when developing

**Supporting Information**

Team Joules has quite some experience setting up these kind of things and are happy to help.
Joules has a setup supporting debugging using F5 in VSCode.
Joules has documented at least parts of there knowledge in their repo.

**Acceptance Criteria**

AC1: A developer has a stable development environment (this probably excludes CodeSpaces and suggests Docker)
AC2: A developer can easily execute the pytest testsuite successfully
AC3: A developer can easily debug any pytest test
AC4: A developer can easily execute the streaming job
AC5: A developer can easily debug the streaming job
AC6: All previous ACs has suitable public documentation
AC7: Intellisense works
AC8: Navigating to declarations works

Nice to have:

AC9: A developer can use the same filesystem in the (devcontainer) environment as on the local machine
      (this enables more flexible file/folder manipulation operations without having to e.g. push/pull a branch)

**Comment by mknic** [comment]
@BjarkeMeier, it might be implicit but we have struggled a lot with IntelliSense and the possibility to navigate between methods etc. This part would be nice to have represented as an `AC` as well as we still struggle to have a consistent environment where IntelliSense works every time.

**Comment by BjarkeMeier** [comment]
Great suggestion @mknic. Thanks, added.

**Comment by HenrikSommer** [comment]
Remarks for review and test:

In general: We have chosen _Visual Studio Code_ and Docker containerization as development environment in the Time Series domain. The use of various VS Code extensions are essential for fulfillment of several AC's.

AC1: A stable development environment is established using Docker
AC2 and 3: Easy execution of the pytest test suite can be carried out with _Python Test Explorer_

AC4 and 5: With the combination of VS Code and Docker a developer can easily run (_Ctrl + F5_) and debug (_F5_) code

AC6: All other ACs have been documented in the Time Series Streaming Job readme.md file

AC7 and 7: Handled by _Python_ and _Pylance_ extensions

Nice to have:
AC9: With Docker and VS Code a developer can easily write new code, run and debug without the push/pull-task. Some operations, like manipulation of container settings require a rebuild of the docker container but this can be performed easily using the _Remote - Containers_ extension.
