### ISSUE TITLE
Ensure data is saved and events are published only once

### ISSUE THREAD

**Issue by lasrinnil** [Energinet-DataHub/geh-timeseries#141]
**Description**
There must be cohesion between saving data and publishing events.

**Tech notes**
Look up the "Outbox pattern" for inspiration and talk with Kristian Fauerskov

**Acceptance criteria**
1) Data must only be saved once
2) Events must only be published if data is saved
3) Events must be published and only be published once

**Comment by PerTHenriksen** [comment]
to be elaborated in refinement session, how much of a risk do we face during actor test phase, if not solved. 
PTH need a bit more business value to prioritize this story
