### ISSUE TITLE
Create wiki structure

### ISSUE THREAD

**Issue by erduna** [Energinet-DataHub/geh-timeseries#17]
Create wiki structure for repo including:

Add | Business workflow description,   e.g. change of supplier, time series submission
-- | --
Add | NFRs – and add referral to geh_repo’s   NFR page
Add | Referral to ADR + Dictionary in   geh_repo

**Comment by BjarkeMeier** [comment]
We have dropped using wiki at the moment. Awaiting decision about wiki vs GitHub Pages or other.
