### ISSUE TITLE
Spike: Use ProtoBuf with PySpark

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/geh-timeseries#172]
**Synopsis**
Evaluate whether ProtoBuf can be used with PySpark.

**Acceptance Criteria**
Criteria does not need to be deployed to nor tested in neither U nor T. Localhost and separate branch will suffice.

1) Messages on the Eventhub is stored in protobuf format
2) The streaming job can consume the protobuf message from the Eventhub
3) The streaming job can validate timeseries in the protobuf format.

**Comment by BjarkeMeier** [comment]
For tester: Code is in branch Use_protobuf_for_received_time_series and usable CIM XML documents exist in the Postman collection. Feel free to reach out to @BjarkeMeier or @HenrikSommer for assistance as needed.

**Comment by BjarkeMeier** [comment]
Btw, I skipped the review stage of the issue as this is only a spike to proof that we are able to use ProtoBuf in PySpark.

**Comment by lasrinnil** [comment]
Test

I've send the message in the postman 
![image.png](https://images.zenhubusercontent.com/60bdfcb3effb2082025638c1/44af31ba-9bac-4619-8e25-1ffb5bb66d32)

Then the streamingjob procssed the data

![image.png](https://images.zenhubusercontent.com/60bdfcb3effb2082025638c1/f76e3678-1d22-4cdf-9519-a74d5ae1f4e0)

verified that valid data was stored.

![image.png](https://images.zenhubusercontent.com/60bdfcb3effb2082025638c1/a40950fe-01b8-4a3c-990f-4d646687befc)
