### ISSUE TITLE
Analysis: Domain modelling of time series domain

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/geh-timeseries#174]
**Synopsis**

Are we modelling the domain in the best way or are we too much inspired by ebiX and DataHub 2?
Let's dive in and analyse what can be improved and what outside constraints we have - like e.g. are all properties that are currently deemed mandatory in CIM XML required even when it doesn't add value to the domain?

**Supporting Questions**

* Are all CIM XML properties needed?
  * Why would the time-series domain want to receive `Document.Type`?
  * Why would the time-series domain want to have a `Document.Receiver`?
  * Why would `Document.Sender` specify a role when we don't want to rely on it or trust it?
  * Why would we have a `MarketParticpantRole` enum for `Document.Sender.Role` if only one single value (MeteredDataResponsible) is valid?
* Are all currently implemented enum values valid and/or needed?

Why is the sender modeled as a generic "market participant" in lieu of a more precise and explicit "metered data responsible"?

What shall we do with data we are not interested in? Skip them? Store them along with the rest of the data? Validate them (what if they are wrong)?

According to the business, there is an unambiguous bi-directional relation between unit and product - so why do we need both information as it seems only as an opportunity for failure and superfluous implementation code and unit tests.

**Acceptance Criteria**

1. CIM XML requirements have been settled and decisions have been made about how to handle data that the domain doesn't need but is obliged to receive
2. Desired model changes have been settled
3. Refactoring stories about desired model changes have been created

**Comment by PerLysemose** [comment]
Dependency to SME
