### ISSUE TITLE
Time series spillover and QA 

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-timeseries#179]
### Estimate

**Comment by PerTHenriksen** [comment]
include latest TI requirements: 
Minimum 4 hours measurements 
15 minute resolution
single measurement can be corrected. 

![image.png](https://images.zenhubusercontent.com/60bdf7bbfa2182da7fd5cc6d/be4820cf-fcf4-4a4a-90ae-f9724861fb0d)

**Comment by MadsBloendAndersen** [comment]
@PerTHenriksen What are we to do with this feature in PI7?
