### ISSUE TITLE
Time Series cim to cim mapping

### ISSUE THREAD

**Issue by PerTHenriksen** [Energinet-DataHub/geh-timeseries#194]
### Description 

Inbound time series message can be of two schemas, Ebix xml or CIM xml. All market parties have agreed to shift from current format, ebix to cim, most of them prior to intended go-live. Received messages needs to be mapped to an internal CIM representation. 

### Acceptance Criteria

- [ ] integrate a CIM to CIM mapper in Datahub
- [ ] Demonstrate an RSM-012 being mapped to CIM, and is passed into the time series domain for processsing. 

### Estimate

**Comment by mogensjuul** [comment]
udgår
