### ISSUE TITLE
Add missing time-series domain test

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-timeseries#217]
**Synopsis**
Cf. the ART decision missing domain tests should be added in the time-series domain.

**Acceptance-Criteria**

AC1:
Given the time-series ingestion endpoint
When receiving a NotifyValidatedMeasureData_MarketDocument CIM XML
Then a HTTP 200 response code is returned

~~AC2:
Given the time-series ingestion endpoint
When receiving a NotifyValidatedMeasureData_MarketDocument CIM XML
Then the time-series is published (made available in public/shared Delta Lake)~~ will be handled later, for the time being we don't know where and how they're published.

**Comment by PerLysemose** [comment]
Tester 200 ok, når vi sender ind
