### ISSUE TITLE
[Charges] Misc SQL tasks - OBS: Probably best done when segregating data model into two (command / query)

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-timeseries#237]
**Acceptance criteria:**

- [ ] Use SQL uniqueue indexes as extensively as possible? (Clarify with SME what is unique in a Charge context)
- [x] Rename in db; Chargre.MarketParticipantId to Charge.OwnerId

**Comment by Mech0z** [comment]
Add missing unique indexes on existing models
