### ISSUE TITLE
UnitTest status in pipelines are hard to read

### ISSUE THREAD

**Issue by lasrinnil** [Energinet-DataHub/geh-timeseries#265]

**Comment by HenrikSommer** [comment]
Mighty Ducks Questions:
https://teams.microsoft.com/l/channel/19%3a3fa44dbb75854b57a4a48936d70743b6%40thread.tacv2/Questions?groupId=38e0432b-6379-40d1-9b3a-b1b90c48de70&tenantId=f7619355-6c67-4100-9a78-1847f30742e2

**Comment by prtandrup** [comment]
I've asked Might Ducks whether they see it as their responsibility to deliver a unit test report in our CI pipelines.

**Comment by prtandrup** [comment]
Mighty Ducks have created an [issue](https://app.zenhub.com/workspaces/mighty-ducks-60ae1565be2dfe0017ff66b2/issues/energinet-datahub/mightyducks/267) for it. Will probably not be prioritized before PI7.
I consider this dev board ticket closed.
