### ISSUE TITLE
Argument checking in methods

### ISSUE THREAD

**Issue by bemwen** [Energinet-DataHub/geh-timeseries#287]

**Comment by bemwen** [comment]
Discussed: The rule enforcing null check will be disabled as the Team does not see the value of it.

**Comment by BjarkeMeier** [comment]
I just removed some argument null checks and have no warnings in Rider and Visual Studio and I can build successfully in both IDEs. So anticipate that we don't have a problem until someone proofs me wrong :-)

Closing issue.
