### ISSUE TITLE
Replace logning with middleware

### ISSUE THREAD

**Issue by lasrinnil** [Energinet-DataHub/geh-timeseries#288]

**Comment by lasrinnil** [comment]
![image.png](https://images.zenhubusercontent.com/60bdfcb3effb2082025638c1/17bd6976-d8c9-40a0-9ff2-8ed7c012c68a)

**Comment by BjarkeMeier** [comment]
Resolved with [this PR](https://github.com/Energinet-DataHub/geh-charges/pull/786).
