### ISSUE TITLE
Optimize use of internal protobuf contracts

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/geh-timeseries#344]
1. Only one contract. Example:
ChargeCommand = ChargeCommandReceived = ChargeCommandAccepted = ChargeCommandRejected.ChargeCommand.

2. Don't repeat enums in contracts
Use int's for enum values and just cast on both sides (serialization and deserialization).

3. And why do we use ProtoBuf internally? Is it still an architect requirement?

**Comment by prtandrup** [comment]
Will be carried out via https://github.com/Energinet-DataHub/geh-charges/issues/938
