### ISSUE TITLE
Determine new naming scheme for time series

### ISSUE THREAD

**Issue by bemwen** [Energinet-DataHub/geh-timeseries#35]
**Description:** 
As we are only obliged to use CIM when communicating with other domains, this story will take the first step towards using more common and easier to understand names when working with Time Series objects within the Time Series domain.
This is also referred to as the [domain language](https://github.com/Energinet-DataHub/green-energy-hub/blob/main/docs/domain-language-guide-book.md). 

This task is similar to what was done for the charges in the Charges domain, see [this](https://github.com/Energinet-DataHub/geh-charges/issues/116).

**Acceptance criteria:** 
AC#1 Naming scheme for time series has been created and approved by Product Owner and SME
AC#2 The dictionary in Green Energy Hub repo has been updated/aligned with the terms in the naming scheme, and definitions have been added for the terms as well.

**Comment by prtandrup** [comment]
Still pending SME approval, but for now:
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/31b39579-ffa6-4d50-a111-2e92a68210d3)

**Comment by BjarkeMeier** [comment]
Perhaps 'ObservationTime` should be `ObservationDateTime` for consistency?

**Comment by prtandrup** [comment]
> Perhaps `ObservationTime` should be `ObservationDateTime` for consistency?

Agreed. Changed in both naming scheme png file above, dictionary and in C# code for TimeSeriesCommand
