### ISSUE TITLE
Prepare infrastructure for receiving CIM/XML time series

### ISSUE THREAD

**Issue by bemwen** [Energinet-DataHub/geh-timeseries#37]
**Synopsis**
We are able to receive a valid CIM/XML timeseries for later processing in the time series domain

**Precondition**
We have received a valid CIM/XML file containing a time series as an example

**Scope**
Make functionality for receiving a CIM/XML time series
We will not be enforcing any structure or rules on it yet, we just make a dummy implementation that takes anything and return success.
We prepare examples in postman for later work.

**Acceptance criteria**
AC 1: We return status 200 on a HTTP post
AC 2: We have a postman example of valid CIM/XML time series message ready in a shared collection

**Comment by PerLysemose** [comment]
- Create MessageReceiver (mapping)
- Terraform + pipeline
- Solution structuring

(Use Batman's solution for xml parser - please check latest state (Søren))
Receive a CIM XML message with multiple time series (Bundled)

**Comment by HenrikSommer** [comment]
Test result: Pass

There is a new workspace in Postman for the Timeseries domain:

![image.png](https://images.zenhubusercontent.com/60bf731f5b600c8c1257787b/023684ea-c593-4d4d-90fc-2bfdca9718e9)

AC 1: MessageReceiver Http endpoint returns 200 OK
AC 2: Postman Timeseries domain workspace contains environments for Development and Test and a new default collection of post requests with CIM/XML body for Timeseries MessageReceiver
