### ISSUE TITLE
Store latest received time-series for aggregations

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-timeseries#376]
Synopsis
---------
As SME|PO
I want to make time-series observations available to the aggregations domain
So that they can later be used in aggregations

Acceptance-Criteria
---------
AC 1:
Given time-series data
When published to the Event Hub
The time-series observations are stored in a Delta Table available for reading by the aggregations domain

AC2:
Given MDR  
When forwarding valid time-series to datahub   
Then only recent values are stored for aggregations 

Tech Notes

- [ ] Move general stuff to NuGet packages
---------
![image.png](https://images.zenhubusercontent.com/60bdfcb3effb2082025638c1/2565929d-3871-437f-815b-aa3faa676c64)

Consider how data are queried from aggregations to time series and construct partitioning accordingly

**Comment by lasrinnil** [comment]
Test
------------------
AC1
Verified through DataBricks workspace.
![image.png](https://images.zenhubusercontent.com/60bdfcb3effb2082025638c1/6863239f-8775-41fe-99d2-47c66b5af889)


AC2
TimeSeries point measurement updated verified going forward in time
![image.png](https://images.zenhubusercontent.com/60bdfcb3effb2082025638c1/d5e94907-7a94-4146-bad3-42aa99aa5885)
TimeSeries point measurement updated verified on same measurement time
![image.png](https://images.zenhubusercontent.com/60bdfcb3effb2082025638c1/b95aff4c-5048-4369-baeb-ff9e6687a9c0)
TimeSeries point measurement not updated when registration date is in the past

**Comment by BjarkeMeier** [comment]
@ZavezX, on which environment?
