### ISSUE TITLE
Databricks can receive and store time series from message receiver (new format)

### ISSUE THREAD

**Issue by bemwen** [Energinet-DataHub/geh-timeseries#38]
**Synopsis**
After the message receiver is implemented with time-series following the new format. The migrated streaming job must be able to consume the messages.

**Prerequisite**
Issue #35
Issue #37

**Technotes**
Remember to empty the Deltalake before inserting data in the new format.

**Acceptance criteria**
AC1: Given the message receiver, when it receives a valid time series message, then the streaming job stores the time series.
AC2: Business terms updated in correspondence to issue #35.
AC3: Enrichment fields must no longer be saved in Delta Lake.
AC4': Given the message receiver, when it receives a _invalid_ time series message, then the streaming job _does not_ stored it.
' AC transferred from #36.

**Comment by prtandrup** [comment]
I cannot test this as Databricks in T environment does not process time series placed on the EventHub.

The Spark standard output log for the Streaming Job shows: 
- No loading/use of master-data.csv 
- No time series processing

Other notes: 
- The databricks job failed to start after pipeline run. => started it manually in azure. 
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/6b41080f-630a-4ac4-bec1-3796807f7453)
- The master-data.csv file present in the storage account where the old file with CIM naming => replaced it with the new master data file from main, restarted the streaming job. 
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/82e914e5-7792-4d48-9302-5f36577e1f32)

- The Log4j throws this warning (not sure the relevance):
`21/07/02 08:20:28 WARN MetastoreMonitor: Failed to connect to the metastore InternalMysqlMetastore(DbMetastoreConfig{host=consolidated-westeuropec2-prod-metastore-0.mysql.database.azure.com, port=3306, dbName=organization8923648768287648, user=[REDACTED]}). (timeSinceLastSuccess=2100009)
java.lang.IllegalArgumentException: A health check named database already exists`

**Comment by BjarkeMeier** [comment]
@prtandrup , this is just based on a very quick search but [here](https://docs.microsoft.com/en-us/answers/questions/335649/spark-job-freezes-without-any-progress-for-a-long.html) someone has the same error message. And 3 weeks ago he still hadn't got a solution for his 1½ month old support ticket.

**Comment by prtandrup** [comment]
**Tested <RESULT> in T environment**
```
Summary:
AC1: OK
AC2: OK
AC3: OK
AC4: Pending - Azure AD issue stopping the launch of databricks workspace in az portal.

Test details provided below
```
**AC1:** Valid time series submitted to the MessageReceiver and Databricks stored them correctly.

**- Timeseries (hourly, 24 values, all values quality = measured) => Stored** :white_check_mark:

_Databricks:_
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/031d48de-606d-4ff1-aa99-fec46ea8994d)

_Storage:_
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/494bfb18-52f6-40e3-ba87-16bfa5e6a739)

**- Timeseries (hourly, 24 values without any quality tags) => Stored as measured (seen as 1)** :white_check_mark: 

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/18de86b0-948a-45f8-89f0-f4aa25a6d32d)


**- Timeseries (hourly, 24 values with quality (position1 = estimated, pos2 = measured and remaining are without quality tag) => Stored with correct quality (3 for estimated, 1 for measured)**  

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/703b8b09-5367-4ef9-8aa0-c816d131c3ab)

**- Timeseries (15min, 96 values, mix of quality values) => Stored** :white_check_mark:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/777613c8-8223-43d9-8487-91c6ea615587)

**- Timeseries (hourly, 2 days of values (48), including missing values) => Stored (missing seen as 4)** :white_check_mark:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/9b25a158-4eb1-4f08-a88b-e247b524468e)

**AC2:** Naming convention applied :white_check_mark: . Al though we need to have a look at the used columns in Delta Lake, not all are necessary in my opinion (existing? or new story)
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/1ae19e91-cba3-4416-860f-1cf8bddcf5f8)

**AC3:** No Enrichment fields present in list. Originally we also saved to the following column, they are no longer present: 
MeteringMethod
MeterReadingPeriodicity
MeteringGridArea_Domain_mRID
ConnectionState
EnergySupplier_MarketParticipant_mRID
BalanceResponsibleParty_MarketParticipant_mRID
InMeteringGridArea_Domain_mRID
InMeteringGridArea_Domain_Owner_mRID
OutMeteringGridArea_Domain_mRID	FromGridArea
OutMeteringGridArea_Domain_Owner_mRID
Parent_Domain_mRID
ServiceCategory_Kind
Technology

**AC4**: Invalid time series submitted to MessageReceiver - processed in Databricks, but not stored:
Suddenly there was a problem reaching the databricks workspace. Seems to be a Azure ID issue. Will continue this test later.
