### ISSUE TITLE
TimeSeries is published to Aggregation domain

### ISSUE THREAD

**Issue by bemwen** [Energinet-DataHub/geh-timeseries#39]
Protobuf and contract/interface settled with Joules

Notes: 
- Time Series Contract is defined [here](https://github.com/Energinet-DataHub/geh-timeseries/blob/main/docs/contracts.md).

**Acceptance criteria:**
- A valid processed time series is published to TimeSeries EventHub (U) according to agreed contract
- A valid processed time series is published to Shared EventHub (T) according to agreed contract
(above was first thoughts by Peter)

**Comment by PerTHenriksen** [comment]
Mangler label ;needs refinement (label mangler i tidsserierepo)

**Comment by BjarkeMeier** [comment]
@PerTHenriksen, was it a mistake that you changed the estimate to 0?

**Comment by BjarkeMeier** [comment]
PRs:
- [Create `protobuf` contract](https://github.com/Energinet-DataHub/geh-timeseries/pull/186)
- [Create shared event hub](https://github.com/Energinet-DataHub/geh-shared-resources/pull/33)
- Create infra for PR|U|development environments
- Publish time series accepted event
