### ISSUE TITLE
Notification from health checks of time series domain (Databricks)

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-timeseries#406]
@MadsBloendAndersen commented on [Thu Feb 17 2022](https://github.com/Energinet-DataHub/geh-aggregations/issues/614)

### Synopsis
As a team
we want monitoring of vital parts in the timeseries domain
so that i can secure efficient operation and debugging of the system

### Acceptance criteria

AC1:
- [x] Given the time series domain
When streaming job is down
Then the bad health status is reported in Teams alert channel (DH 3 operations team channel)

**Comment by PerLysemose** [comment]
@ftoft vil du ikke få tilføjet taskliste

**Comment by ftoft** [comment]
Tasklist

- [ ] Implement a databricks endpoint client, able to parse json and return running jobs
- [ ] Implement custom health check able to check if a specific job is running on databricks
- [ ] Move all config parameters so it is not hardheaded any more
- [ ] Test notification is working as expexted, we shuld have a notification on a teams channel

**Comment by lasrinnil** [comment]
I have verified that the health check is working as intended:

if stopping either or both of the streaming jobs (persister/publisher) the ingestor function becomes unhealthy and a message is sent in teams on the according to team channel

**Comment by MadsBloendAndersen** [comment]
@lasrinnil i have a few question regarding this issue: 

1. Is the health check deployed and tested in T001? 
2. Where can i find the alert that has been sent to the teams channel "Alerts-TEST-001". If we can find the alert from your test, then we probably don't have to go through it again with a demo.
3. If found this alert (Not sure if it's the right one though): 
![image](https://user-images.githubusercontent.com/72008712/184625467-232444da-0871-4ac8-9b9b-10a3ab03babb.png)
but it states that the health check comes from func-time-series-bundle-ingestor-timeseries-t-001. Is that in databricks as the title suggests?
