### ISSUE TITLE
Health monitoring of time series domain (.NET)

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-timeseries#425]
### Synopsis
As a team
we want monitoring of vital parts in the timeseries domain
so that i can secure efficient operation and debugging of the system

### Acceptance Criteria

AC1:

Given the time series domain
When ingestor or eventhub connection is down 
Then the bad health status is reported in Teams alert channel (DH 3 operations team channel)

### Tech Notes

Use [this package](https://teams.microsoft.com/l/message/19:Z45YOniw4YUFEnENKgbKOHgtjbf1axySzUZ_jivnYiU1@thread.tacv2/1647506528777?tenantId=f7619355-6c67-4100-9a78-1847f30742e2&groupId=38e0432b-6379-40d1-9b3a-b1b90c48de70&parentMessageId=1647506528777&teamName=Mighty%20Ducks%20-%20Public&channelName=General&createdTime=1647506528777).
Inspiration from [this PR](https://github.com/Energinet-DataHub/geh-charges/pull/1213).

https://github.com/Energinet-DataHub/greenforce-art/blob/main/wiki/monitor/app-service-health-check.md

**Comment by kristianschneider** [comment]
Her kan man se health check:
https://portal.azure.com/#@energinet.onmicrosoft.com/resource/subscriptions/7b7ffd68-d27e-4c75-936a-2653ecc36450/resourceGroups/rg-datahub-timeseries-t-001/providers/Microsoft.Web/sites/func-time-series-bundle-ingestor-timeseries-t-001/appServices

Her kan man se alert:
https://portal.azure.com/#blade/Microsoft_Azure_Monitoring/AlertVNextRulesViewModel/queryInputs/%7B%22subscriptions%22%3A%227b7ffd68-d27e-4c75-936a-2653ecc36450%22%2C%22resourceGroupId%22%3A%22%2Fsubscriptions%2F7b7ffd68-d27e-4c75-936a-2653ecc36450%2FresourceGroups%2Frg-datahub-timeseries-t-001%22%2C%22resourceId%22%3A%22%2Fsubscriptions%2F7b7ffd68-d27e-4c75-936a-2653ecc36450%2FresourceGroups%2Frg-datahub-timeseries-t-001%2Fproviders%2FMicrosoft.Web%2Fsites%2Ffunc-time-series-bundle-ingestor-timeseries-t-001%22%7D

**Comment by ZavezX** [comment]
I checked that healt monitoring is up and running in azure and it all looks good.

**Comment by MadsBloendAndersen** [comment]
@BjarkeMeier + @ZavezX are we able to see an alert enter this channel? 
![image](https://user-images.githubusercontent.com/72008712/162692225-de39953b-2c5f-4102-84d2-da861d2b7fc9.png)

**Comment by ZavezX** [comment]
@BjarkeMeier @MadsBloendAndersen When I look at the code implementation both the readiness and the live monitoring is set up for both the health check endpoint as well as the eventhub live check. The alert part is also set up in the deployment files, so as I mentioned in my other comment, it all looks good.

If you look at the links from Kristians comment, the alert is set up in azure and the health check is applied to the bundle ingestor function.

**Comment by BjarkeMeier** [comment]
Quoting Knuth: "Beware of bugs in the above code; I have only proved it correct, not tried it."

**Comment by ZavezX** [comment]
Jeg har tvunget en alert igennem ved at fjerne en konfiguration til event hub, som resulterede i en besked i teams kanalen:
![Teams_r4RYsAjGrW.png](https://images.zenhubusercontent.com/60dae1a8503a837b772b93a5/393208aa-9c6b-467f-ac24-c680014dfacb)

Ved at stoppe vores function i azure kom der ingen besked i teams kanalen, men om det er normalen ved jeg ikke.

**Comment by BjarkeMeier** [comment]
Sounds like the story fails on the AC 1 part "when ingestor is down". We should care about that.

**Comment by ZavezX** [comment]
I think we should ask MightyDucks if this is the default behaviour, because the code is implemented as documented.

**Comment by ZavezX** [comment]
I tested again today to see if we would get notified if a function was depoloyed but failed on start. I got an alert in the teams channel as seen on the image below:
![image.png](https://images.zenhubusercontent.com/60dae1a8503a837b772b93a5/fc962ed6-b673-491c-b536-f8b793b8f29f)
