### ISSUE TITLE
PySpark integrationtest are run in pipeline in TimeSeries

### ISSUE THREAD

**Issue by lasrinnil** [Energinet-DataHub/geh-timeseries#430]
Synopsis
----------------
Developers of team joules want to run integration tests of PySpark jobs in PR-gate to ensure stability and a fast and steady development cycle.

Acceptance criteria
----------------------
- [x] TimeSeries PySpark integration tests are verified in PR-gate
- [x] GreenForce Developers can run integration tests localhost by following documents
- [x] GreenForce Developers can debug integration tests by following the documentation

Tasklist
-----------------
- [x] Update CI pipeline to support pytest integrationtest of PySpark code
- [x] Add/update all relevant documentation

**Comment by BjarkeMeier** [comment]
From [testing ](https://github.com/Energinet-DataHub/geh-timeseries/runs/5694259480?check_suite_focus=true) that PR gate now fails for the right reasons when integration tests fail:

![image.png](https://images.zenhubusercontent.com/60c2e712ae37899de9483e3a/89a153cc-0979-4ec6-84d3-67f6200cec3e)

![image.png](https://images.zenhubusercontent.com/60c2e712ae37899de9483e3a/ca3927fc-e508-46a3-8f67-1f46fdd41d13)

**Comment by ZavezX** [comment]
Alle accept kriterier synes at være opfyldt.
