### ISSUE TITLE
Remaning Integrationtest of PySpark in TimeSeries

### ISSUE THREAD

**Issue by lasrinnil** [Energinet-DataHub/geh-timeseries#432]
Synopsis
----------------
To ensure stability and high confidence that our streaming jobs are working as intended. Team Joules want to cover all
PySpark jobs with integration tests.

Acceptance criteria
----------------
- [ ] All PySpark jobs in TimeSeries are covered by sufficient integration tests
- [ ] All TimeSeries PySpark integration tests are verified in PR-gate

Tech Notes
----------------
- Test flow from `un-processed-timeseries` to `processed-timeseries`
    - Validate that all inserted data in `un-processed-timeseries` is present in `processed-timeseries`
    - Validate schema in `processed-timeseries`
- Test flow from eventhub to `un-processed-timeseries`
    - Validate received data from eventhub is present in `un-processed-timeseries`
    - Validate schema in `un-processed- timeseries`

**Comment by MadsBloendAndersen** [comment]
@lasrinnil will fill in synopsis + acceptance criteria

**Comment by MadsBloendAndersen** [comment]
@kristianschneider will bring this issue to tech refinement
