### ISSUE TITLE
[Cancelled] Do not break environments when avoidable

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/geh-timeseries#464]
Synopsis
---------------------
As an operations organization
I don't want environments to break by deploying bad deployments
So that the users (b2b and b2c) have a stable system
and I don't get unecessary critical incidents

Acceptance-Criteria
---------------------------
- [ ] AC1
Given a deployment
When it breaks the [health check|system test|other criteria?] of a given environment
Then the deployment is not deployed to subsequent environments

**Comment by PerTHenriksen** [comment]
Given the risk: https://app.zenhub.com/workspaces/risk-board-60e57f2388bfed000ebdf573/issues/energinet-datahub/internal-repo/29 - please keep assignees of this risk in the loop - both regarding refinement and implementation.
