### ISSUE TITLE
Cross Team work/Pair Programming

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-timeseries#51]
**Suggestions regarding Databricks:**

1. Joules has gained a lot of knowledge and experience while we have forgotten our learnings. Things have changed, libraries have been outdated or even vanished. I would like time for the team to get input from Joules on our implementation.
2. Joules has planned work on investigating and set up the optimal dev environment for Databricks development. Joules and I would like to work together on that (at least the investigation part)

**Comment by PerTHenriksen** [comment]
input from Bjarke, extend the databricks experience and have sparing with Joules.
