### ISSUE TITLE
Support for bundled CIM/XML messages from Market Participants in time series domain

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-timeseries#57]
**Synopsis:**
We want to support bundled ingestion messages in the timeseries domain so that market participants are able to send multiple timeseries in one message to the time series domain.

**Acceptance Criteria:**
* It is possible to send a notify validated measurements with multiple bundled timeseries in one message to the time series domain
~~* It is ensured that changes in a bundle which affect the same metering point, are applied in the same order as they appeared in the bundled message~~ out of scope for this story

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/215be4c1-1b31-4cca-9504-a50baea09248)

* Green box indicates primary location affected by this functionality
* Yellow box indicates potential affected parts.

**Comment by PerTHenriksen** [comment]
remember that old repo contains a similar solution.
