### ISSUE TITLE
Preparation work for making a data contract between Time Series and Aggregations domains

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-timeseries#66]
**Description:**
First step towards having a time series data contract to be used between the Time Series and Aggregations domains.

**Precondition:** 
- A list containing data requirements received from code owners of the Aggregations domain; what is expected to be published by the time series domain.

**Acceptance criteria:** 
AC#1 Based on the list, a draft text document has been created containing: 
- The properties, their data types, possible null values, 
~~- And when we expect to throw event(s) conforming to the data contract~~
AC#2 Draft document has been shared with the Aggregations code owners before the 'Data contract session'.
AC#3 Draft document is attached to this story in GitHub.

**Comment by PerTHenriksen** [comment]
Preparation for workshop.

**Comment by prtandrup** [comment]
**AC#1 + AC#3:** draft documented can be found below. The png file has the drawio file embedded within:
![20210621-Timeseries-Aggregation domain data contract.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/0b6eda87-de2c-40bf-8766-35a1c2672a82)

AC#2: Draft document was shared with the Aggregations code owners before the meeting.

The part "when the event" is thrown/published, has been moved to another story (#90)

**Comment by bemwen** [comment]
Test result:
AC1 - PASSED
AC2 - PASSED
AC3 - PASSED

AC1:
The draft document has been created as required.

AC2:
The document was shared with the aggregation domain before the mentioned meeting.

AC3:
The draft document is attached as a comment to this story.

**Comment by BjarkeMeier** [comment]
A few thoughts:
- Notes are not in english
- Perhaps two lines of explanation of the drawing would be helpful for others or when later referring back to this issue
