### ISSUE TITLE
Time series data contract session with Aggregations domain code-owners

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-timeseries#67]
**Description:** 
Code-owners of Time Series and Aggregations domains align on a data contract content for time series.

**Precondition:**
- Story #66 is a predecessor

**Acceptance criteria**
- Meeting done
- Further data contract development stories have been created and the responsibility of completing those are clear.

**Comment by prtandrup** [comment]
Meeting held today, 18-06-2021
New story added to TimeSeries backlog #90

**Comment by bemwen** [comment]
Test result:
AC1 - PASSED
AC2 - PASSED

AC1:
Meeting held as per previous comment.

AC2:
Story has been created and responsibility of this story is mentioned.
