### ISSUE TITLE
Redundant Domain test requirement, replaced by ny stories.. : Ensure time series persistence happy flow (working software)

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/geh-timeseries#69]
**Synopsis**
Once established we want to make sure that the happy flow of receiving and storing valid time series is never broken.

**Prerequisites**
- #38
- The team has knowledge about how to execute intra domain tests in PR gateway (#142)

**Tech Notes**
Please consider reusing at least parts of the work that Mads has already done - e.g. the functionality to read parquet from Delta Lake.

**Acceptance Criteria**
AC1: Given the time-series domain, when receiving a valid time series, then the time series is stored
AC2: The integration test guards breaking the main branch by being part of the PR gateway
to be delteted: The test is executed as part of PR gateway

**Comment by PerLysemose** [comment]
Message Receiver to be included in the existing test
