### ISSUE TITLE
Parse timeseries and place on EventHub

### ISSUE THREAD

**Issue by bemwen** [Energinet-DataHub/geh-timeseries#72]
**Synopsis**
When the domain receive a CIM/XML time series we parse it and put in on the eventhub for processing in DataBricks

**Precondition**
#35 has been completed
#37 has been implemented

**Scope**
We create a parser for the CIM/XML time series structure and place a new message on an eventhub based on our new time series naming scheme.
Because time series is the domain with the largest amount of throughput, the XML parser should be efficient and make sure of the strategy defined earlier in the old shared green-energy-hub-archived repository.
Schema validation of the CIM/XML and similar validations are out of scope, we only need to implement the required functionality to handle a valid CIM/XML time series.

**Acceptance criteria**
AC 1: When a valid CIM/XML time series message with a single time series is received, a message is placed on an EventHub
AC 2: The message placed on the event hub adheres to the time series naming scheme (see #35)
AC 3: The CIM/XML parser must be based on XmlReader as this ensure efficient parsing.

**Notes**
See https://github.com/Energinet-DataHub/ARCHIVED-green-energy-hub/blob/main/samples/energinet/soap-to-json-adapter/source/Energinet.DataHub.SoapAdapter.Application/Converters/TimeSeriesConverter.cs for example of previous XmlReader based implementation of an eBIX time series

**Comment by prtandrup** [comment]
**For reviewers:** https://github.com/Energinet-DataHub/geh-timeseries/pull/106

TimeSeries CIM XML requests are available in Postman in our TimeSeries Domain work space.

This was tested locally against my sandbox and the message placed on EventHub looks like this (shortened to 5 positions):

```json
[
  {
    "Document": {
      "Id": "DocId2021-06-24T10:36:33.548Z",
      "RequestDateTime": "2021-06-24T10:36:33.5747672Z",
      "Type": 1,
      "CreatedDateTime": "2021-06-24T10:36:33.5480000Z",
      "Sender": {
        "Id": "8100000000030",
        "BusinessProcessRole": 4
      },
      "Recipient": {
        "Id": "5790001330552",
        "BusinessProcessRole": 3
      },
      "BusinessReasonCode": 4
    },
    "Series": {
      "Id": "tId2021-06-24T10:36:33.548Z",
      "MeteringPointId": "578032999778756222",
      "MeteringPointType": 1,
      "SettlementMethod": 3,
      "RegistrationDateTime": "2021-06-24T10:36:33.5480000Z",
      "Product": 5,
      "Unit": 1,
      "Resolution": 2,
      "StartDateTime": "2021-06-27T22:00:00.0000000Z",
      "EndDateTime": "2021-06-28T22:00:00.0000000Z",
      "Points": [
        {
          "Position": 1,
          "ObservationDateTime": "2021-06-27T22:00:00.0000000Z",
          "Quantity": 0.337,
          "Quality": 1
        },
        {
          "Position": 2,
          "ObservationDateTime": "2021-06-27T23:00:00.0000000Z",
          "Quantity": 1.683,
          "Quality": 5
        },
        {
          "Position": 3,
          "ObservationDateTime": "2021-06-28T00:00:00.0000000Z",
          "Quantity": 2.016,
          "Quality": 3
        },
        {
          "Position": 4,
          "ObservationDateTime": "2021-06-28T01:00:00.0000000Z",
          "Quantity": 3.895,
          "Quality": 2
        },
        {
          "Position": 5,
          "ObservationDateTime": "2021-06-28T02:00:00.0000000Z",
          "Quantity": 4.124,
          "Quality": 1
        }
      ]
    },
    "Transaction": {
      "MRID": "4158069d0f044550bd2161db365ce77e"
    },
    "CorrelationId": "7519fd87-b971-4c9b-aed9-f9649c8517b0",
    "EventProcessedUtcTime": "2021-06-24T10:36:59.6718830Z",
    "PartitionId": 9,
    "EventEnqueuedUtcTime": "2021-06-24T10:36:33.5820000Z"
  }
]
```

**Comment by prtandrup** [comment]
Ready for test in T. 
Request is available in Postman in Timeseries domain work space, ensure you are targeting the T environment like this:
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/cbadf93b-5880-4460-ab88-f0e648691b89)
